### ISSUE TITLE
[Bug]: Onesignal 5.1.5, 5.1.6 could not be resolved in iOS Swift Package Manager

### ISSUE THREAD

**Issue by jenbitcoin** [OneSignal/OneSignal-iOS-SDK#1424]
### What happened?

We are currently using this version 3.12.9 -- and wanted to updated our package. The latest ones I saw today were 5.1.5, and 5.1.6. The thing is that it could not be resolved. And I get some errors on checksum not matched and fatalError.

I tried Resolving SPM, I tried clearing cache, removed derived data (clean out trash), restart xcode. And lastly, I tried removing OneSignal from our SPM. Build the project. Re-add OneSignal to our SPM which automatically points to latest version. But it still doesn't work.
![Screenshot 2024-05-02 at 3 23 16 PM](https://github.com/OneSignal/OneSignal-iOS-SDK/assets/52556996/a14932d1-8c8a-4480-9dcc-2913d390b0ce)
![Screenshot 2024-05-02 at 3 23 31 PM](https://github.com/OneSignal/OneSignal-iOS-SDK/assets/52556996/e49f0c2b-2cf6-44cf-a412-45c879535ae4)

But if I revert back to OneSignal 3.12.9, everything works out well, and I can build the project again successfully:

### Steps to reproduce?

```Markdown
1. Just by updating OneSignal (v 3.12.9) to 5.1.5 or 5.1.6 via SPM - doesn't work.
2. Xcode version 15.0
```

### What did you expect to happen?

Should be able to update to latest OneSignal version.

### OneSignal iOS SDK version

 3.12.9

### iOS version

16

### Specific iOS version

```Markdown
I was testing / building it in Xcode using iOS Simulator 16.4 (and it didn't work, in fact, I could not add / update to the latest OneSignal version)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by djavan-bertrand** [comment]
Same problem with me. To fix it, I set the package to the `exact` version of 5.1.4.

**Comment by nan-li** [comment]
HI @jenbitcoin and @djavan-bertrand, thank you for reporting.
We released version 5.1.6 recently and made an update to the files. Did you also clear SPMs package cache?
```
~/Library/Caches/org.swift.swiftpm/repositories
```

I am surprised version 5.1.5 is an issue for you as well. We released that version 2 weeks ago and made no changes to it.

**Comment by kunalzigma** [comment]
Cannot add Sdk in new app.
<img width="746" alt="File1714812336222" src="https://github.com/OneSignal/OneSignal-iOS-SDK/assets/22952744/8fcc8189-1ade-4cd5-acc2-724ea4475b56">

**Comment by artem-tverdokhlebov** [comment]
same problem, for now will stick to 5.1.4

**Comment by nan-li** [comment]
Can reporters running into this confirm that running `~/Library/Caches/org.swift.swiftpm/repositories` did not work?

**Comment by kunalzigma** [comment]
Have removed OneSignal-XCFramework-75c1bc28 & OneSignal-XCFramework-fe10aafb folders from `~/Library/Caches/org.swift.swiftpm/repositories` 
Now seeing this. 
Still not able to add. 
<img width="1104" alt="Screenshot 2024-05-07 at 11 44 02 PM" src="https://github.com/OneSignal/OneSignal-iOS-SDK/assets/22952744/1319b5f0-f759-4307-9190-7240e0f91c60">

**Comment by jenbitcoin** [comment]
Apologies for the late reply, I have slow internet the past few days and updating SPM was such a nightmare and blocks me from doing my tasks. I'll try again today and see if 5.1.4 works.

As for the recent releases, I had cleared cache, removed derived data, deleted trash and it was not working. I also asked another teammate to update OneSignal to latest version and she encountered the same issue with me.

**Comment by kunalzigma** [comment]
Hi,
We really had schedule of a major update for our app completed last week and release this week, and eagerly needed push notifications. We are able to add 5.1.5 with exact version. Done the testing, setup, and everything with 5.1.5. But really needed the 5.1.6 as we don't know when we will be updating the app next. 
Similarly after the release of a newer 13 inch iPad, we will pushing updates to 3 other apps with onesignal. 

So, we humbly request you to sort out this for us and others.

**Comment by nan-li** [comment]
Hi everyone, I'm not sure why this is not working for people reporting. What xcode version are you using?

I am using xcode 15.2, and cleaning all my package caches was sufficient to add version 5.1.6. 

We do plan to release 5.1.7 this week, but version 5.1.6 may also be added via commit: `fc88833146e426eb4f64806baf5e494212458cad` as it corresponds to its [Release 5.1.6](https://github.com/OneSignal/OneSignal-XCFramework/releases/tag/5.1.6). 

![Screenshot 2024-05-08 at 10 34 01 AM](https://github.com/OneSignal/OneSignal-iOS-SDK/assets/4022291/ae3c3b67-fc0f-41e9-89b9-7fcbd17af367)

**Comment by kunalzigma** [comment]
Am on xcode 15.3 , and still same issue with adding that above SHA1 in commit. See the same as in the screenshot i provided before.

**Comment by kunalzigma** [comment]
If 5.1.7 will be released this week, i can wait, but now the information is there, that this issue was happening with xcode 15.3. Hope that you take care of this with the new version.

**Comment by nan-li** [comment]
I just tested with xcode 15.3, and was able to get the package. 

Something with SPM is odd for some users, but I am not sure what... maybe some other configuration.

From the screenshots, the checksums indicate that SPM is returning an outdated / cached package for v5.1.6 as those are the old checksums. We updated the packages and checksums 7 days ago, so this downloaded package it is returning is over 7 days old.

The checksums we have currently are correct, and the correct packages are hosted, so I am not sure what we can do from our end. 

SPM is grabbing the old packages and comparing the checksums to the current values.

**Comment by nan-li** [comment]
I'm looking for similar issues online, can you try these steps?

- removed an old onesignal-xcframework
- chose 'Up to Next Major Version' for a new onesignal-xcframework
- deleted derived data folder
- rm -rf ~/Library/Caches/org.swift.swiftpm
- rm -rf ~/Library/Caches/com.apple.dt.*
- only after that tapped 'add package'

**Comment by artem-tverdokhlebov** [comment]
@nan-li on this commit, the command "swift package resolve" works, but on the previous isn't. Seems like its trying to work with the commit which has tag on it. Maybe this will help?

<img width="773" alt="image" src="https://github.com/OneSignal/OneSignal-iOS-SDK/assets/1665709/bb86d0f4-0b18-45b1-a957-e7c693744587">

**Comment by nan-li** [comment]
Hmm @artem-tverdokhlebov, interesting,

I did not update that tag as the the [Package.swift ](https://github.com/OneSignal/OneSignal-XCFramework/blob/5.1.6/Package.swift) file for v5.1.6 of the **onesignal-xcframework** indicates to go to, for example:

> https://github.com/OneSignal/OneSignal-iOS-SDK/releases/download/5.1.6/OneSignalFramework.xcframework.zip


And the correct zips with the correct checksums live there. SPM should just be downloading [the assets that live on that release](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.1.6).

Ah. You know what.... just as I typed that.... I looked at screenshots again and realized users are adding the dependency via `onesignal-ios-sdk`?

Our [ios setup instructions](https://documentation.onesignal.com/docs/ios-sdk-setup#swift-package-manager) indicate to use Enter Package URL: `https://github.com/OneSignal/OneSignal-XCFramework`.

I did not realize users were adding it via **this** repository as well, which thinking about it, makes sense that people would do this.

**Comment by nan-li** [comment]
I am updating the release and tag in this repository, but anyone encountering this issue can use Package URL: https://github.com/OneSignal/OneSignal-XCFramework

**Comment by dfmuir** [comment]
@nan-li using https://github.com/OneSignal/OneSignal-XCFramework resolved this issue for me and allowed me to install 5.1.6.

**Comment by artem-tverdokhlebov** [comment]
As I look at the previous replies, I can see that users were clearly adding https://github.com/OneSignal/OneSignal-XCFramework, but still encountered this issue. However, it seems to be working now. Thanks, @nan-li!

**Comment by kunalzigma** [comment]
And @nan-li , you can already in the screenshots, i was using the right url , the whole time. Even artem confirmed that.

**Comment by nan-li** [comment]
Hi @kunalzigma I'm sorry you are experiencing such a headache.

I see some people such as the original poster do appear to be using `OneSignal-iOS-SDK`. I am not sure what issue you are running into. I downloaded 5.1.6 on the day it released in an example project, and then updated it the next day after we fixed some code signatures in the SDK. I ran into the checksum errors but running smoe clearing commands worked for me:

```
rm -rf ~/Library/Caches/org.swift.swiftpm
rm -rf ~/Library/org.swift.swiftpm
rm -rf ~/Library/Developer/Xcode/DerivedData
```

I read that `rm -rf ~/Library/Caches/com.apple.dt.*` is also a command that worked for some people.

Have you tried running all 4 of these commands together?

**Comment by kunalzigma** [comment]
@nan-li the first 3 commands worked for me. I was able to get 5.1.6. Didnt need the 4th command. Thanks. Because 5.1.6 was performing great in one of our app added on 1st may , i needed it.  But as you had announced 5.1.7 is around the corner, will be needing that too. Hopefully it comes out soon.

**Comment by nan-li** [comment]
Hi @kunalzigma that's great to hear those commands worked! We just released [Release 5.2.0](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.2.0) which includes a new feature for Push to Start Live Activities amongst other updates.

I'll close out this issue, feel free to @ me if you run into any problems.
