### ISSUE TITLE
[Bug] Crash when logging in-app message impression

### ISSUE THREAD

**Issue by kajensen** [OneSignal/OneSignal-iOS-SDK#1453]
### What happened?

I'm seeing reports of a subset of my users crashing when logging a OneSignal in-app message impression.
<img width="579" alt="Screenshot 2024-06-19 at 10 59 47 AM" src="https://github.com/OneSignal/OneSignal-iOS-SDK/assets/6947273/2206a848-fd45-4b17-ad8b-54be6ca591b9">

This is a re-opening of #937

### Steps to reproduce?

```Markdown
I haven't reproduced myself but the crash logs indicate it happens when an in-app message is shown. Early indications show that it appears to be limited to iOS 17.5.1 devices.
```

### What did you expect to happen?

No crash

### OneSignal iOS SDK version

5.1.6

### iOS version

17

### Specific iOS version

```Markdown
iOS 17.5.1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kajensen** [comment]
Update: also seeing crashes on 17.4.1

**Comment by emawby** [comment]
@kajensen Thank you for reporting we will investigate

**Comment by kunalzigma** [comment]
this should be resolved immediately, we are fed up of all these crashes. Already lost many users in another app due to crashes and cannot afford to lose more in this one where it is happening.
You might have seen other users removing onesignal from their apps on these sdk issues. You are already losing business due to this.
Dont force us to do the same. 
Or please provide alternatives to Onesignal. 
we cannot afford more crashes of such kind. 
instead of gaining business, we are losing after adding OneSignal. Never faced any such issue with any 3rd party SDK that too paid in past 13 years of development. This is too much and unbearable.
Cant you provide crash free experience for atleast a year or so? Is that really difficult? 
please say it to my face, leave onesignal. Dont harass me. 
This is torture and harassment. 
Instead of focussing on new features, you should be have made it bug-free.

**Comment by edsonbittencourt** [comment]
I'm having problems migrating my app from iOS 17 to iOS 18 and Mac Sequoia, where the scenario is as follows: if the OneSignal framework is installed in the app, I can't run it in Xcode 16, as the app generates multiple errors/crashes.

By completely removing the OneSignal package, everything works normally, and I can build/run my app perfectly.

The problem is that I can't use Xcode 15.4 anymore unless I roll back my OS. Therefore, I can't send app updates.

I don't know if it's related to the problem, but it's quite complicated to maintain the use of the OneSignal framework.

**Comment by kunalzigma** [comment]
I have paused InApp messages from my app because saw 2 more crashes just now. We were showing first IAM on first app start by any user after which push prompt shows. Will pausing avoid crashes until , i can expect an update?  I dont care if subscribers are added. I just dont want any more crashes. Is that possible with this?

**Comment by nan-li** [comment]
Hi @edsonbittencourt can you open a new issue with details about your errors?

**Comment by nan-li** [comment]
Hi @kunalzigma, if you use the SDK method `OneSignal.InAppMessages.paused = true` and set this upon initialization, IAMs will not display and this crash will not occur.

Just wondering, did you recently delete users or subscriptions?

**Comment by kunalzigma** [comment]
I have paused from the console. Will that work in avoiding crashes? I wont be getting subscribers because push prompt is shown after IAM until this is resolved.Whats the ETA for this to be resolved? Kindly atleast let us know. No, i didnt even touch or delete any users / subscriptions. Its strange it is happening to my last added app suddenly. On 27 Jun 2024, at 9:19 PM, Nan ***@***.***> wrote:﻿
Hi @kunalzigma, if you use the SDK method OneSignal.InAppMessages.paused = true and set this upon initialization, IAMs will not display and this crash will not occur.
Just wondering, did you recently delete users or subscriptions?

**Comment by nan-li** [comment]
@kajensen @kunalzigma Are you seeing this only on iOS 17.5.1?
We are resolving and investigating as you did not delete any users or subscriptions.

**Comment by kajensen** [comment]
@nan-li at least 17.4.1 as well

**Comment by kunalzigma** [comment]
@nan-li i am seeing 4 crashes. 3 in one app, 2 in 17.5.1 , and 1 in 17.4.1, whereas the other app, 1 crash in 17.5.1

**Comment by kajensen** [comment]
@nan-li This has affected over 200 users for us, so doesn't appear to be isolated. Please let us know if we can help investigate as this is a priority for us to fix asap and it has already been over a week.

**Comment by kajensen** [comment]
> @kajensen Thank you for reporting we will investigate

Any reports or information you can share regarding the investigation? This has been open over a week and is a priority for us to fix asap.

**Comment by kunalzigma** [comment]
Another crash that too on the app which had those previous other crashes. 5 crashes on 3 apps.

**Comment by emawby** [comment]
The fix has been released in version 5.2.2

**Comment by AlexSaraev** [comment]
The same crash occurs in 5.2.6 when the device is offline.
Exception Reason: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]
iOS 18.0.1

**Comment by pierrolivier** [comment]
I also have the same problem after updating to version 5.2.6. I didn't have this problem with the previous version. The crash occurs when the app is open.

`NSInvalidArgumentException
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1`

`CoreFoundation +0x827cc __exceptionPreprocess`
`OneSignalCore +0x0a06c -[OneSignalClient handleJSONNSURLResponse:data:error:isAsync:withRequest:onSuccess:onFailure:]`
`OneSignalCore +0x09338 __54-[OneSignalClient executeRequest:onSuccess:onFailure:]_block_invoke`
`Called from CFNetwork +0x6b9c0 __40-[__NSURLSessionLocal taskForClassInfo:]_block_invoke`

**Comment by amoshsueh** [comment]
Same issue in 5.2.7

<img width="1161" alt="截圖 2024-11-17 下午2 06 55" src="https://github.com/user-attachments/assets/51a68db1-eda6-46e7-afaf-fbe04d83f13d">

**Comment by ronee12** [comment]
This crash still happening in 5.2.7. Please fix this ASAP.

![Screenshot 2024-11-26 at 12 05 05 PM](https://github.com/user-attachments/assets/aa5442a0-282a-4962-ad45-0c998b03db36)

**Comment by ahmedsafadii** [comment]
@emawby Any update about it ?

**Comment by solibe1** [comment]
@emawby updatess?

**Comment by nan-li** [comment]
The new crash reports on 5.2.6 and 5.2.7 are fixed in [Release 5.2.9](https://github.com/OneSignal/OneSignal-iOS-SDK/releases/tag/5.2.9)
