### ISSUE TITLE
Occasional Crash At App Launch Getting Subclass

### ISSUE THREAD

**Issue by jstheoriginal** [OneSignal/OneSignal-iOS-SDK#274]
My app keeps crashing at launch (maybe 5% of the time) when the SDK calls this method in file OneSignalSelectorHelpers.m:

```
NSArray* ClassGetSubclasses(Class parentClass) {
    
    int numClasses = objc_getClassList(NULL, 0);
    Class *classes = NULL;
    
    classes = (Class *)malloc(sizeof(Class) * numClasses);
    numClasses = objc_getClassList(classes, numClasses);
    
    NSMutableArray *result = [NSMutableArray array];
    for (NSInteger i = 0; i < numClasses; i++) {
        Class superClass = classes[i];
        do {
            superClass = class_getSuperclass(superClass);
        } while(superClass && superClass != parentClass);
        
        if (superClass == nil) continue;
        [result addObject:classes[i]];
    }
    
    free(classes);
    
    return result;
}
```

The crash occurs in this line:

`superClass = class_getSuperclass(superClass);`

**Comment by jkasten2** [comment]
@jstheoriginal Can you provide the full stack trace of the crash? Include the iOS version, OneSignal SDK version, and if you are using any other frameworks in your project.

Can you reproduce the issue in a new Xcode project?

**Comment by laurent-humbert** [comment]
Same here, although it's more like 50% of the time. This is with Xcode 9 GM and iOS 11. If I run the app using the iOS 10 simulator it's fine. I removed all calls to OneSignal and left the framework, and it still crashed.

**Comment by jstheoriginal** [comment]
Will grab the stack trace once it happens again. 

I’m using the latest version of OneSignal.
And I only call a single OneSignal method in my app on a pushed screen (it never crashes then...always before the app has finished launching, so it must be some OneSignal Singleton init issue).

Like Laurent says, it’s onky happening on iOS 11 and happens on the Xcode 9 GM release.

I *think* it might only happen in the simulator. 

Laurent: have you had it crash on physical device or just in the sim?

**Comment by anushkmittal** [comment]
Same here, This is with Xcode 9 GM/iOS 11, and latest SDK version. Also exact situation as @jstheoriginal

**Comment by jkasten2** [comment]
@anushkmittal @laurent-humbert I tried reproducing this issue with the latest GM of iOS 11.0 and Xcode 9 without success. Both with Carthage builds and Cocoapods. As well as on a simulator and a real device.

Can you try example project or a clean new Xcode to see if the crash still happens for you?
https://github.com/OneSignal/OneSignal-iOS-SDK/tree/master/Examples

Please let us know all other frameworks you are using in your project. Lastly are you using `UNNotificationCenterDelegate` any where in your code?

**Comment by anushkmittal** [comment]
Did you try it out on an iPhone X simulator? Also, I ran a workspace search for `UNNotification` and the only occurrences were in `OneSignalNotificationServiceExtension`. I'll link the reproducible Xcode project soon

**Comment by jkasten2** [comment]
@anushkmittal Was testing on an iPhone 8 simulator and an a real iPhone 6 on iOS 10.0. Just tried an iPhone X simulator without any issues. The device models shouldn't be a factor.

What method did you use the setup the OneSignal SDK? Cocoapods, Carthage, or manually?

**Comment by jstheoriginal** [comment]
I’m using Carthage to install the SDK.

**Comment by laurent-humbert** [comment]
I did a manual install. I just grabbed the iOS_SDK/OneSignalSDK/Framework/OneSignal.framework file from the SDK and added it to both the app and notification extension targets.

Today I also added Foundation.framework, CFNetwork.framework, SystemConfiguration.framework and UIKit.framework to the extension target, and it *looks* like it fixed the problem....

**Comment by jkasten2** [comment]
@laurent-humbert Odd that Xcode isn't getting a link error without those 4 frameworks added to the project. When it was crashing was it also happening on `class_getSuperclass`? If you still have the stack trace saved was it the same as "anushkmittal"'s?

Did the crash only happen when ran the extension target? Or only when you receive a notification with mutable-content enabled, action buttons, or media attachment feature?

**Comment by jstheoriginal** [comment]
I wasn't sending any push notifications when it crashes...it just crashes on app launch. Seems to be unrelated to actual pushes coming in at all.

**Comment by jkasten2** [comment]
@jstheoriginal Does launching your app from Xcode through the normal app target vs the notification extension have an effect if crashes or not?

**Comment by jstheoriginal** [comment]
I don't have an extension...just a normal app target.

**Comment by jstheoriginal** [comment]
These are the frameworks I use:

<img width="523" alt="screen shot 2017-09-18 at 2 30 57 pm" src="https://user-images.githubusercontent.com/5117473/30560609-15323138-9c7e-11e7-93a6-0479205d0cd7.png">

**Comment by allaire** [comment]
Just happened to me on the simulator (iPhone 6, Xcode 9):

![screen shot 2017-09-21 at 09 13 00](https://user-images.githubusercontent.com/304461/30697483-26686bd0-9ead-11e7-8c05-9006a3bc947f.png)

**Comment by jkasten2** [comment]
The issue is now fixed in master. It will be included in the next release.

**Comment by atom-wintermute** [comment]
@jkasten2, I try to use this fix

pod 'OneSignal', :git => 'https://github.com/OneSignal/OneSignal-iOS-SDK', :commit => 'd6157d582a992c2bed27aa7aab445d30772f312b'

with same result:
![screen shot 2017-09-22 at 09 44 27](https://user-images.githubusercontent.com/18706680/30727364-01c4d718-9f7b-11e7-82a0-5a16f22912a2.png)

It's doesn't help

**Comment by hixfield** [comment]
When is the next release planned? Should we in the meanwhile use master or is this not recommended? I am releasing a new version of my app in the next days...

**Comment by alexandre-g** [comment]
Also experiencing crashes on launch on simulator - sometimes often sometimes rarely. Haven't tried on device. Pulled in the framework gerbiljames kindly built on his fork (https://github.com/OneSignal/OneSignal-iOS-SDK/issues/278#issuecomment-332208704)

which has the aforementioned fix, but the issue still happening for me and the second iOS dev in office.

![image](https://user-images.githubusercontent.com/9635561/30952411-234b1bf0-a46b-11e7-84f0-c1f83f78c13d.png)

**Comment by gerbiljames** [comment]
Yeah it's still happening for me too with the framework on my fork. We got through approval using it though so we were either lucky or it doesnt happen on device.

**Comment by hixfield** [comment]
Do you have crashreporting in you appon the store? Could you use it to verify that it does not crash on the actual device?

**Comment by michael-gillett** [comment]
I am also getting the same error after apply the fix. I will try and generate a crashreport to see whats up

**Comment by YBthebest** [comment]
Just jumping in to confirm I am having this exact same issue.

**Comment by jkasten2** [comment]
Version 2.5.5 as been released to CocoaPods with a fix for this.

If their are any future issues please post to issue https://github.com/OneSignal/OneSignal-iOS-SDK/issues/278 instead.
