### ISSUE TITLE
Unable to build for deployment target ios 9.0

### ISSUE THREAD

**Issue by aravasio** [OneSignal/OneSignal-iOS-SDK#280]
Following the step-by-step guide for the iOS SDK, I can get everything up and running as long as deployment targets are >10, but as soon as I put it to 9.0, I start getting the following kind of error:
>'UNNotificationRequest' is only available on iOS application extension 10.0 or newer
and I'm forced to add >@available(iOSApplicationExtension 10.0, *)

so it can build.
How can I provide support for the iOS9 devices without denying them Push Notifications altogether? I'm assuming this is partly due to the fact that iOS10 has the Rich Notifications system.

**Comment by vzsg** [comment]
If you are following the guide precisely, you have added a notification service extension to your project. That extension's deployment target must be at least 10.0, but you can set your application project to 9.0 **separately**, and both versions will work fine.

**Comment by jkasten2** [comment]
@aravasio Vzsg's answer should fix the error your are seeing. Feel free to reopen the issue if this doesn't help.

**Comment by lexuanquynh** [comment]
how to implement for ios 9?

**Comment by Nightsd01** [comment]
@lexuanquynh I’m not sure what you are asking....?

**Comment by simmatrix** [comment]
@vzsg so by setting my extension's deployment target to 8.0, do I still need to add `API_AVAILABLE(ios(10.0))` (as suggested by XCode) in order by to silence the warning?

**Comment by simmatrix** [comment]
@vzsg Thank you for the clarification. So for users below iOS 10, they can still receive push notifications, it's just that we would not be able to show image and action buttons in notifications?

**Comment by vzsg** [comment]
That's right, those extras will not be available in the Notification Center, but it will work at a basic level.

**Comment by ajRiverav** [comment]
@vzsg is there a list of things one gains if the app's deployment target is 9.0 and IS bumped to 10.0? You just mentioned two here: show images and action buttons as part of a notification. We are debating whether to bump ours up.
